# NOTE: Set via environment variable
# server:
#   address: 'tcp://0.0.0.0:9091'
 
log:
  level: info
  format: text
  file_path: /config/authelia.log
  keep_stdout: true
 
totp:
  issuer: authelia.com
  period: 30
  skew: 1
 
authentication_backend:
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 128
 
# https://www.authelia.com/overview/authorization/access-control/
access_control:
  default_policy: deny
  rules:
    - domain: 'auth.mydomain.com'
      policy: 'two_factor'
 
# https://www.authelia.com/configuration/session/introduction/
session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: mydomain.com
 
regulation:
  max_retries: 3
  find_time: 300
  ban_time: 600
 
storage:
  local:
   path: /config/db.sqlite3
 
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notifications.txt