services:
  threadfin:
    image: fyb3roptik/threadfin
    container_name: threadfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./threadfin/conf:/home/threadfin/conf
      - ./threadfin/temp:/tmp/threadfin:rw
      - /mnt/nas:/mnt/nas
    ports:
      - 34400:34400
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    gpus: all
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.8
    volumes:
      - ./jellyfin:/config
      - /data:/data
      - /mnt/nas:/mnt/nas
    ports:
      - 8096:8096
      - 7359:7359/udp # Service Discovery
      - 1900:1900/udp # Client Discovery
    runtime: nvidia
    gpus: all
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.9
    volumes:
      - ./jellyseerr:/app/config
      - /mnt/nas:/mnt/nas
    ports:
      - 5055:5055
    restart: unless-stopped

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.10
    volumes:
      - ./jellystat/postgres:/var/lib/postgresql/data
      - /mnt/nas:/mnt/nas
    restart: unless-stopped

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      TZ: ${TZ}
    volumes:
      - ./jellystat/backup-data:/app/backend/backup-data
      - /mnt/nas:/mnt/nas
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - jellystat-db
