services:
  tuliprox:
    container_name: tuliprox
    image: ghcr.io/euzu/tuliprox:latest
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - ./tuliprox/data:/app/data
      - ./tuliprox/config:/app/config
      - ./tuliprox/backup:/app/backup
      - ./tuliprox/downloads:/app/downloads
      - ./tuliprox/user-config:/app/user-config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8901:8901
    depends_on:
      - gluetun
    runtime: nvidia
    gpus: all
    network_mode: service:gluetun
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app", "-p", "/app/config", "--healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 
