networks:
  internalnetwork:
    external: true

  externalnetwork:
    external: true

services:
  # TODO: Add notification app
  # TODO: Add check updates app

  scrutiny-db:
    image: influxdb:2.8
    container_name: scrutiny-db
    ports:
      - 8083:8086
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${SCRUTINY_DATABASE_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${SCRUTINY_DATABASE_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=scrutiny
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${SCRUTINY_DATABASE_TOKEN} 
    volumes:
      - ./scrutiny-db/database:/var/lib/influxdb2
      - ./scrutiny-db/config:/etc/influxdb2
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.20
    healthcheck:
      test: curl -s http://localhost:8086/health
      interval: 5s
      timeout: 10s
      retries: 20
    restart: unless-stopped

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - SCRUTINY_WEB_INFLUXDB_HOST=172.39.0.20
      - SCRUTINY_WEB_INFLUXDB_TOKEN=${SCRUTINY_DATABASE_TOKEN}
      - SCRUTINY_WEB_INFLUXDB_ORG=homelab
      - SCRUTINY_WEB_INFLUXDB_BUCKET=scrutiny
      # Optional but highly recommended to notify you in case of a problem; space-separated list of shoutrrr uri's
      # https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_NOTIFICATIONS.md
      # - SCRUTINY_NOTIFY_URLS=http://gotify:80/message?token=a-gotify-token ntfy://username:password@host:port/topic
    volumes:
      - ./scrutiny:/opt/scrutiny/config
    ports:
      - 8082:8080
    depends_on:
      scrutiny-db:
        condition: service_healthy
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.21
    healthcheck:
      test: curl -s http://localhost:8080/api/health
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    restart: unless-stopped
