networks:
  internalnetwork:
    external: true

  externalnetwork:
    external: true

services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_USERNAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_PASSWORD}
      - GOTIFY_SERVER_PORT=81
      - GOTIFY_SERVER_SSL_PORT=444
    volumes:
      - ./gotify:/app/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8070:81
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.20
    healthcheck:
      test: curl http://localhost:81/health
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_GOTIFY_ENDPOINT=http://172.39.0.20:81
      - DIUN_NOTIF_GOTIFY_TOKEN=${DIUN_GOTIFY_TOKEN}
      - DIUN_NOTIF_GOTIFY_PRIORITY=1
      - DIUN_NOTIF_GOTIFY_TIMEOUT=10s
      - DIUN_NOTIF_GOTIFY_TLSSKIPVERIFY=true
      - DIUN_NOTIF_GOTIFY_TEMPLATETITLE={{ .Entry.Image }} released
      - DIUN_NOTIF_GOTIFY_TEMPLATEBODY=Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
    volumes:
      - ./diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.21
    healthcheck:
      test: sh -c "ping -c1 1.1.1.1 && ping -c1 172.39.0.20"
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: always
  
  # TODO: Dashboard (pulse)

  scrutiny-db:
    image: influxdb:2.8
    container_name: scrutiny-db
    ports:
      - 8083:8086
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${SCRUTINY_DATABASE_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${SCRUTINY_DATABASE_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=scrutiny
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${SCRUTINY_DATABASE_TOKEN} 
    volumes:
      - ./scrutiny-db/database:/var/lib/influxdb2
      - ./scrutiny-db/config:/etc/influxdb2
      - /etc/localtime:/etc/localtime:ro
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.23
    healthcheck:
      test: curl -s http://localhost:8086/health
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - SCRUTINY_WEB_INFLUXDB_HOST=172.39.0.23
      - SCRUTINY_WEB_INFLUXDB_TOKEN=${SCRUTINY_DATABASE_TOKEN}
      - SCRUTINY_WEB_INFLUXDB_ORG=homelab
      - SCRUTINY_WEB_INFLUXDB_BUCKET=scrutiny
      - SCRUTINY_NOTIFY_URLS=http://172.39.0.20:81/message?token${SCRUTINY_GOTIFY_TOKEN}
    volumes:
      - ./scrutiny:/opt/scrutiny/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8082:8080
    depends_on:
      scrutiny-db:
        condition: service_healthy
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.24
    healthcheck:
      test: curl -s http://localhost:8080/api/health
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 10s
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped
