# =============================================================================
# NAT, outbound masquerade and inbound port forwards
# =============================================================================
chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;

    # Masquerade all internal VLAN traffic going to the internet.
    ip saddr $NET_ALL_INTERNAL oifname $WAN_IF masquerade
}

chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;

    # Inbound HTTP/HTTPS -> DMZ reverse proxy.
    iifname $WAN_IF tcp dport $PORTS_HTTP dnat to $IP_PUBNET

    # Add additional port forwards here, like:
    # iifname $WAN_IF tcp dport $PORT_JELLYFIN dnat to $IP_MEDIA   # Direct Jellyfin
}
