networks:
  priv-net-network:
    name: priv-net-network
    external: true

services:
  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    # user: ${PUID}:${PGID} # This container runs better as root
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./certs:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      priv-net-network:
        ipv4_address: 172.24.1.10
    healthcheck:
      test: pgrep -f docker-entrypoint
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"] # Custom entrypoint for auto-renewing certificates
    restart: unless-stopped
