networks:
  arr-network:
    name: arr-network
    external: true

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    # user: ${PUID}:${PGID} # This container run as non-root already
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
      - PORT=8192
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:vpn1
    healthcheck:
      test: sh -c "curl https://www.google.com && curl -s http://localhost:8192/health" # curl https://www.google.com checks internet connectivity instead of ping and nslookup, because this container doesn't have them
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    # user: ${PUID}:${PGID} # This container runs as 1000:1000 already
    environment:
      - LOG_LEVEL=INFO
      - TZ=${TZ}
      - PORT=8193
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:vpn1
    healthcheck:
      test: sh -c "curl https://www.google.com && curl -s http://localhost:8193/health" # curl https://www.google.com checks internet connectivity instead of ping and nslookup, because this container doesn't have them
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s
    restart: unless-stopped

  flaresolverr-aggregate:
    image: ghcr.io/ggjorven/flaresolverr-aggregate:latest
    container_name: flaresolverr-aggregate
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
      - FLARESOLVERR_URL=http://172.24.1.10:8192/v1
      - BYPARR_URL=http://172.24.1.10:8193/v1
    networks:
      arr-network:
        ipv4_address: 172.24.1.12
    ports:
      - "0.0.0.0:8191:8191"
    depends_on:
      - flaresolverr
      - byparr
    restart: unless-stopped
