networks:
  arr-network:
    name: arr-network
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    # user: ${PUID}:${PGID} # linuxserver containers handle this with environment PUID, PGID
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:vpn1
    healthcheck:
      test: sh -c "ping -c1 1.1.1.1 && nslookup www.google.com && wget -qO- http://localhost:9696 && curl -s http://localhost:9696/ping"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: unless-stopped
