networks:
  internalnetwork:
    name: internalnetwork
    ipam:
      config:
        - subnet: 172.39.0.0/24

  externalnetwork:
    name: externalnetwork
    ipam:
      config:
        - subnet: 172.40.0.0/24

services:
  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    user: ${PUID}:${PGID}   
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    network_mode: "none"
    healthcheck:
      test: ["CMD", "/app", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always

  vpn1: # Main VPN, torrenting + the rest
    image: qmcgaw/gluetun
    container_name: vpn1
    # user: ${PUID}:${PGID} # This container requires to run as root
    cap_add:
      - NET_ADMIN
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=openvpn
      - FIREWALL_OUTBOUND_SUBNETS=172.39.0.0/24 # Make the VPN able to talk over the internalnetwork, this is needed for some people
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${VPN1_REGIONS}
      - DNS_SERVER=on
      - DNS_UPSTREAM_RESOLVERS=cloudflare,google,quad9 # Makes the DNS requests to random resolvers 
      - HEALTH_VPN_DURATION_INITIAL=${HEALTH_VPN_DURATION_INITIAL}
      - VPN_PORT_FORWARDING=${VPN1_PORT_FORWARDING:-off}
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c "echo My forwarded ports are {{PORTS}}, the first forwarded port is {{PORT}} and the VPN network interface is {{VPN_INTERFACE}}" 
    volumes:
      - ./vpn1:/gluetun
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080 # qbittorrent web interface
      - 6789:6789 # nzbget web interface
      - 9696:9696 # prowlarr web interface
      - 9191:9191 # dispatcharr web interface
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.10
    healthcheck:
      test: sh -c "ping -c1 1.1.1.1 >/dev/null 2>&1 && nslookup www.google.com"
      interval: 30s
      timeout: 10s
      retries: 5
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  vpn2: # Secondary VPN, soulseek
    image: qmcgaw/gluetun
    container_name: vpn2
    # user: ${PUID}:${PGID} # This container requires to run as root
    cap_add:
      - NET_ADMIN
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=openvpn
      - FIREWALL_OUTBOUND_SUBNETS=172.39.0.0/24 # Make the VPN able to talk over the internalnetwork, this is needed for some people
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${VPN2_REGIONS}
      - DNS_SERVER=on
      - DNS_UPSTREAM_RESOLVERS=cloudflare,google,quad9 # Makes the DNS requests to random resolvers 
      - HEALTH_VPN_DURATION_INITIAL=${HEALTH_VPN_DURATION_INITIAL}
      - VPN_PORT_FORWARDING=${VPN2_PORT_FORWARDING:-off}
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c "echo My forwarded ports are {{PORTS}}, the first forwarded port is {{PORT}} and the VPN network interface is {{VPN_INTERFACE}}" 
    volumes:
      - ./vpn2:/gluetun
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5030:5030 # slskd web interface
      - 5031:5031 # slskd HTTP
      - 50300:50300 # slskd HTTPS
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.11
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: sh -c "ping -c1 1.1.1.1 >/dev/null 2>&1 && nslookup www.google.com"
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    # user: ${PUID}:${PGID} # This container requires joining another containers network
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:vpn1
    healthcheck:
      test: sh -c "curl -s http://localhost:8191 >/dev/null 2>&1 && curl -s http://localhost:8191/health"
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped
