#!/bin/bash

"$(dirname "$0")/down-metube.sh"
"$(dirname "$0")/down-bazarr.sh"
"$(dirname "$0")/down-lidarr.sh"
"$(dirname "$0")/down-sonarr.sh"
"$(dirname "$0")/down-radarr.sh"
"$(dirname "$0")/down-prowlarr.sh"
"$(dirname "$0")/down-jackett.sh"
"$(dirname "$0")/down-slskd.sh"
"$(dirname "$0")/down-qbittorrent.sh"
"$(dirname "$0")/down-byparr.sh"
"$(dirname "$0")/down-vpn2.sh"
"$(dirname "$0")/down-vpn1.sh"
"$(dirname "$0")/down-monitoring.sh"
"$(dirname "$0")/down-networking.sh"
