networks:
  internalnetwork:
    external: true

  externalnetwork:
    external: true

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich-server
    user: ${PUID}:${PGID}   
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - UPLOAD_LOCATION=${IMMICH_UPLOAD_LOCATION}
      - DB_HOSTNAME=172.39.0.83
      - REDIS_HOSTNAME=172.39.0.82
      - DB_DATABASE_NAME=immich-database
      - DB_USERNAME=${IMMICH_POSTGRES_USER}
      - DB_PASSWORD=${IMMICH_POSTGRES_PASSWORD}
      - DB_DATA_LOCATION=./immich-postgres
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    depends_on:
      - immich-redis
      - immich-database
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.80
    gpus: all
    runtime: nvidia
    healthcheck:
      test: immich-healthcheck
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true  
    restart: always

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-machine-learning
    # user: ${PUID}:${PGID} # Requires root for GPU access
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - IMMICH_VERSION=${IMMICH_VERSION}
      - UPLOAD_LOCATION=${IMMICH_UPLOAD_LOCATION}
      - DB_HOSTNAME=172.39.0.83
      - REDIS_HOSTNAME=172.39.0.82
      - DB_DATABASE_NAME=immich-database
      - DB_USERNAME=${IMMICH_POSTGRES_USER}
      - DB_PASSWORD=${IMMICH_POSTGRES_PASSWORD}
      - DB_DATA_LOCATION=./immich-postgres
    volumes:
      - ./immich-ml-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.81
    runtime: nvidia
    gpus: all
    healthcheck:
      test: python3 healthcheck.py
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: always

  immich-redis:
    image: docker.io/valkey/valkey:9@sha256:930b41430fb727f533c5982fe509b6f04233e26d0f7354e04de4b0d5c706e44e
    container_name: immich-redis
    # user: ${PUID}:${PGID} # Redis requires full root control 
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.82
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: always

  immich-database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich-database
    # user: ${PUID}:${PGID} # The database requires full control
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_DB=immich-database
      - POSTGRES_USER=${IMMICH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${IMMICH_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ./immich-postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    shm_size: 128mb
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.83
    healthcheck:
      test: /usr/local/bin/healthcheck.sh
      interval: 20s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: always

  # TODO: Nextcloud
