networks:
  internalnetwork:
    external: true

  externalnetwork:
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # user: ${PUID}:${PGID} # This container requires joining another containers network
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - DOCKER_MODS=${QBITTORRENT_MODS:-}
      - PORTCHECKER_GLUETUN_API_KEY=${GLUETUN_PORTCHECKER_API_KEY:-}
      - PORTCHECKER_SLEEP=120
      - PORTCHECKER_KILL_ON_NOT_CONNECTABLE=true
    volumes:
      - ./qbittorrent:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:vpn1
    healthcheck:
      test: sh -c "ping -c1 8.8.8.8 >/dev/null 2>&1 && nslookup www.google.com >/dev/null 2>&1 && curl -s http://localhost:8080 || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    # user: ${PUID}:${PGID} # This container requires joining another containers network
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./nzbget:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:vpn1
    healthcheck:
      test: sh -c "ping -c1 8.8.8.8 >/dev/null 2>&1 && nslookup www.google.com >/dev/null 2>&1 && curl -s http://localhost:6789 || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true 
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    user: ${PUID}:${PGID}   
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - STATE_DIR=/config
      - DOWNLOAD_DIR=${METUBE_DOWNLOAD_DIRECTORY}
      - CREATE_CUSTOM_DIRS=false # Stops metube from re-creating the download directories with wrong permissions
      - CHOWN_DIRS=false # Stop metube from changing permissions of download directories
    ports:
      - 8081:8081
    volumes:
      - ./metube:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.30
    healthcheck:
      test: curl -s http://localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  slskd: 
    image: slskd/slskd
    container_name: slskd
    user: ${PUID}:${PGID}
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - SLSKD_SLSK_USERNAME=${SOULSEEK_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SOULSEEK_PASSWORD}
      # - SLSKD_SLSK_DESCRIPTION=Cool description about you
      - SLSKD_DOWNLOADS_DIR=${SLSKD_DOWNLOAD_DIRECTORY}
      - SLSKD_INCOMPLETE_DIR=${SLSKD_INCOMPLETE_DIRECTORY}
      - SLSKD_SHARED_DIR=${SLSKD_SHARED_DIRECTORY:-}
      - SLSKD_SLSK_LISTEN_IP_ADDRESS=0.0.0.0
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_VPN=true
      - SLSKD_VPN_PORT_FORWARDING=${SLSKD_VPN_PORT_FORWARDING:-false}
      - SLSKD_VPN_POLLING_INTERVAL=500
      - SLSKD_VPN_GLUETUN_URL=http://172.39.0.11:8000
      - SLSKD_VPN_GLUETUN_API_KEY=${VPN_API_KEY}
      - SLSKD_UPLOAD_SLOTS=${SLSKD_UPLOAD_SLOTS:-5}
      - SLSKD_UPLOAD_SPEED_LIMIT=${SLSKD_UPLOAD_SPEED_LIMIT:-5000}
      - SLSKD_API_KEY=${SLSKD_API_KEY}
    volumes:
      - ./slskd:/app
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:vpn2
    healthcheck:
      test: wget -qO- http://localhost:5030/healthcheck
      interval: 60s
      timeout: 3s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped
