networks:
  internalnetwork:
    external: true

  externalnetwork:
    external: true

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: ${PUID}:${PGID}   
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - ND_LOGLEVEL=info
      - ND_LISTENBRAINZ_BASEURL=http://172.39.0.62:9078/1/ # Scrobbles to multi-scrobbler
    volumes:
      - ./navidrome:/data
      - ${MUSIC_FOLDER}:/music:ro
      # - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 4533:4533
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.60
      externalnetwork:
        ipv4_address: 172.40.0.60
    healthcheck:
      test: wget -qO- http://localhost:4533
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  metadata-remote:
    image: ghcr.io/wow-signal-dev/metadata-remote:latest
    container_name: metadata-remote
    # user: ${PUID}:${PGID} # Untested without root
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SHOW_HIDDEN_FILES=true
    volumes:
      - ${MUSIC_FOLDER}:/music
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8338:8338
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.61
    healthcheck:
      test: wget -qO- http://127.0.0.1:8338/health
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: multi-scrobbler
    # user: ${PUID}:${PGID} # Untested without root
    environment:
      - PUID=${PUID}
      - PGID=${PGID} 
      - TZ=${TZ}
      - LZE_TOKEN=${NAVIDROME_LB_TOKEN}
    volumes:
      - ./multi-scrobbler:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9078:9078
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.62
    healthcheck:
      test: curl http://localhost:9078/api/health
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
