networks:
  internalnetwork:
    external: true

  externalnetwork:
    external: true

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: ${PUID}:${PGID}   
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - ND_LOGLEVEL=info
    volumes:
      - ./navidrome:/data
      - ${MUSIC_FOLDER}:/music:ro
      # - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 4533:4533
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.60
      externalnetwork:
        ipv4_address: 172.40.0.60
    healthcheck:
      test: wget -qO- http://localhost:4533 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  metadata-remote:
    image: ghcr.io/wow-signal-dev/metadata-remote:latest
    container_name: metadata-remote
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SHOW_HIDDEN_FILES=true
    volumes:
      - ${MUSIC_FOLDER}:/music
    ports:
      - 8338:8338
    networks:
      internalnetwork:
        ipv4_address: 172.39.0.61
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8338/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
    restart: unless-stopped
